### ISSUE TITLE
Regarding dataset

### ISSUE THREAD

**Issue by mradul2** [ICVGIP-Challenge/NetworkQuantization-21#2]
Hello!
It would be very helpful if you provide a direct link (maybe a Google Drive link) for the ImageNet ILSVRC 2012 validation set used for the task?

**Comment by mradul2** [comment]
Even after downloading the official validation dataset of ImageNet ILSVRC 2012 and using it to run main.py raised the following error: 

```
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    test_loader = get_testloader(args.dataset, bs=args.test_bs)
  File "NetworkQuantization-21/dataset.py", line 28, in get_testloader
    normalize,
  File "/opt/conda/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 313, in __init__
    is_valid_file=is_valid_file)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 221, in find_classes
    return find_classes(directory)
  File "/opt/conda/lib/python3.7/site-packages/torchvision/datasets/folder.py", line 42, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in imagenet-val.
```

All 50000 validation images are present in the ` imagenet-val ` directory as provided by the official source.

**Comment by pksvision** [comment]
'imagenet-val' directory should have the images within the labeled sub-folders (representing each class). For this, please refer to the following:

https://github.com/pytorch/examples/tree/master/imagenet

and move validation images to labeled subfolders, using

https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh

Once done, provide the path to 'imagenet-val' directory.
